export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
